### PR TITLE
bump wagmi to 0.4

### PR DESCRIPTION
**Pull request by scottrepreneur**
- bumps wagmi to `v0.4.1`
- named object notation for hooks
- a couple ts tweaks

### CODE REVIEW

**Comment by Geczy** [comment]
why isnt this merged?

**Comment by RusseII** [comment]
LGTM. Can this be merged in?

**Comment by obstropolos** [comment]
> LGTM. Can this be merged in?

Thanks all for the adds / review. Will review right now to get this in.

**Comment by obstropolos** [comment]
Update here - running the branch and getting the following when hitting the "Sign In" button: 

```
Error: invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.6.1)
```

**Comment by scottrepreneur** [comment]
Give this another shot @obstropolos. Letting `RainbowKit` handle the wallets (a bit out of the scope of this example, but easier than setting up connectors manually with `wagmi`)

**Comment by obstropolos** [comment]
> Give this another shot @obstropolos. Letting `RainbowKit` handle the wallets (a bit out of the scope of this example, but much easier than setting up connectors manually with `wagmi`)

Working for me now. 

Can this be cleaned up to only support MetaMask / avoid adding any Infura points for WC? Maybe the connect wallet button is implicitly the injected provider, in this case, to not disturb anything on the UI side [thank you!].

**Comment by Geczy** [comment]
id love for rainbowkit to stay pls

**Pull request merged**
